### ISSUE TITLE
Text Deskew

### ISSUE THREAD

**Issue by tr4nquility** [dlemstra/ImageMagick.FredsScripts.NET#17]
Hi @dlemstra ,
Could you please convert the Text Deskew script?
Original script can be found at [http://www.fmwconcepts.com/imagemagick/textdeskew/index.php](url)
Thanks.

**Comment by mmangiamusardo** [comment]
Hi @dlemstra,
I did a draft conversion of Text Deskew script. 
For the first part (generating spectrum by FFT) I used Emgu (OpenCV).
After that:
var match = imageWithDots.SubImageSearch(new MagickImage($"xc:gray{valpct}", width: 1, height: 1), ErrorMetric.RootMeanSquared);
is really really slow.
Is there any alternative?

Thanks

**Comment by dlemstra** [comment]
Closing this issue because Text Deskew uses forward fourier transform and that is not available due to licensing issues.
