### ISSUE TITLE
Port of Fred Weinhaus's Multicrop script to .Net

### ISSUE THREAD

**Issue by SimonKravis** [dlemstra/ImageMagick.FredsScripts.NET#25]
I would like to use Fred Weinhaus's Multicrop script from a C# application - if it could be ported over that would be much appreciated.

**Comment by Suncatcher** [comment]
Support this, also would like to use it on Windows

**Comment by dlemstra** [comment]
This script is now available in this package: https://www.nuget.org/packages/ImageMagick.FredsScripts.Multicrop.
