### ISSUE TITLE
TextCleanerScript returning blank page

### ISSUE THREAD

**Issue by starnutoditopo** [dlemstra/ImageMagick.FredsScripts.NET#35]
I'm trying to clean some page, but the TextCleanerScript outputs a blank page.

Debugging the source code, I noticed that the problem is in the ```RemoveNoise``` method, when calling ```Negate```.

It seems that the problem is caused by the Alpha channel, so I added a line to fix it:

```C#
        private void RemoveNoise(IMagickImage<TQuantumType> image)
        {
            using (var second = image.Clone())
            {
                second.ColorSpace = ColorSpace.Gray;
                second.Alpha(AlphaOption.Off); // <- Added this line to fix
                second.Negate();
                second.AdaptiveThreshold(FilterSize, FilterSize, FilterOffset);
                second.ContrastStretch((Percentage)0);

                if (SmoothingThreshold != null)
                {
                    var max = _factory.Quantum.Max.ToDouble(null);
                    second.Blur(SmoothingThreshold.Value.ToDouble() / 100, max);
                    second.Level(SmoothingThreshold.Value, new Percentage(100));
                }

                image.Composite(second, CompositeOperator.CopyAlpha);
            }

            image.Opaque(_factory.Colors.Transparent, BackgroundColor);
            image.Alpha(AlphaOption.Off);
        }
```

Maybe the 

```
            image.Opaque(_factory.Colors.Transparent, BackgroundColor);
            image.Alpha(AlphaOption.Off);
```

should be performed at the beginning of the method, BEFORE cloning the image?

**Comment by starnutoditopo** [comment]
Thank you.
A sample image is in attachment.

![image_4](https://user-images.githubusercontent.com/1422525/221868434-66131b45-5a70-4bf5-8d4f-e901d7445248.png)

ps.: At the moment I'm just experimenting with this tool; if it suits the requirements for the project I'm working on, then some people of the commercial team will deal with licencing.

**Comment by dlemstra** [comment]
I have updated the script and added a unit test to make sure this stays fixed. Thanks for reporting this.
